### PR TITLE
Update test.pl --psql-bin option to match command-line help.

### PR DESCRIPTION
**Pull request by k-zshiba**
This is a small change. The name of variable representing the path to the psql executables showed in help command is different from the one accutually used in test script. To make it clear that it is the path to the psql executables, I changed the name of the variable to receive to psql-bin.

### CODE REVIEW

**Review by dwsteele — APPROVED** [review]
Not sure how those got disconnected, but this looks like a good change.

How would you like your name to appear in the release notes?

**Comment by k-zshiba** [comment]
> Not sure how those got disconnected, but this looks like a good change.

Thank you for checking.

> How would you like your name to appear in the release notes?

My name is "Koshi Shibagaki".
Would you use this name is the release notes?

**Comment by dwsteele** [comment]
> Would you use this name is the release notes?

Yes, done in 22238e5e8c77f5.

**Comment by dwsteele** [comment]
Merged, thanks!

**Pull request merged**
