### PR TITLE
Fix SFTP renaming failure when file already exists.

### PR DESCRIPTION
**Pull request by jreidthompson**
Update error handling for libssh2_sftp_rename_ex in storageWriteSftpClose for file already exists. During development and testing the sftp servers never returned file already exists (#define LIBSSH2_FX_FILE_ALREADY_EXISTS 11UL), rather they returned LIBSSH2_FX_FAILURE 4UL when a file already existed.  Issue https://github.com/pgbackrest/pgbackrest/issues/2376 reflects returning  file already exists. Also made an update where storageSftpPathCreate may similarly return file already exists.

### CODE REVIEW

**Review by dwsteele — APPROVED** [review]
This looks OK to me. Seems like you want to try the same server/version the user is using before committing this?

**Comment by jreidthompson** [comment]
> This looks OK to me. Seems like you want to try the same server/version the user is using before committing this?

If possible yes, to see if I can flush out any other cases where it differs from the original dev/test environments.

**Comment by jreidthompson** [comment]
Per comment in the issue, the sftp storage is https://www.hetzner.com storage-box.  I created an account and verified that prior to code changes the issue error occurred and that after code changes the following commands complete successfully. 

stanza-create
check
info
backup full
backup incr
backup diff
info
repo-ls
repo-ls recurse
verify
restore

**Comment by dwsteele** [comment]
So this is ready for commit?

**Comment by jreidthompson** [comment]
> So this is ready for commit?

Yes, it's ready.

**Pull request merged**
