### PR TITLE
Add backup type filter to info command.

### PR DESCRIPTION
**Pull request by pgstef**
Support `--type` option in info command to display only a specific backup type.

### CODE REVIEW

**Comment by dwsteele** [comment]
Seems simple enough. Is this in reference to some specific issue or ask? In brief, what's the use case? I mostly see this as being useful for filtering on full backups.

**Comment by pgstef** [comment]
Indeed, I wanted to compare the performance hit by filtering at the code level rather than in an external perl command (or using jq) to fetch only a specific type of backups.

And since it was in the [backlog](https://github.com/pgbackrest/pgbackrest/projects/2#card-13503164) and closed [issue](https://github.com/pgbackrest/pgbackrest/issues/600), I gave it a try.

I also mostly sees it having benefits for full backups but it doesn't seem to cost much to support all types.

Thanks for the review :-)

**Comment by dwsteele** [comment]
I don't think we have any options that are filtering the JSON data yet. Are we sure this is something we want to do?

**Comment by pgstef** [comment]
> I don't think we have any options that are filtering the JSON data yet. Are we sure this is something we want to do?

Can't `--stanza` and `--repo` already been considered as filters ? 
Currently `--set` is on hold but it would be nice to get there at some point.

Why would the backup-type filter be an issue in JSON output ?
From a monitoring point-of-view, it's very common to only look at full backups :man_shrugging:

**Review by dwsteele — APPROVED** [review]
Made some help edits in e60a770c28a. If those look good this is ready to commit.

**Comment by pgstef** [comment]
> Made some help edits in [e60a770](https://github.com/pgbackrest/pgbackrest/commit/e60a770c28a4731e1880bfffa68363f0c9e45d44). If those look good this is ready to commit.

Looks great to me. Thanks !

**Comment by hunleyd** [comment]
thanks for tackling this @pgstef ! and thanks for the heads up to come look at it @dwsteele . this looks great to me.

**Pull request merged**
