### PR TITLE
Allow custom config-path default with ./configure --with-configdir.

### PR DESCRIPTION
**Pull request by mschout**
This adds --with-confdir=DIR option to configure, which can be used to
override the deafult configuration directory of /etc/pgbackrest

Probably in the future it would be better to just leverage ${sysconfdir}
which is based on prefix, but since previously the config dir was hard
coded to /etc/pgbacrest, we retain that default value by not relying on
sysconfdir for now.

refs #1251

### CODE REVIEW

**Comment by dwsteele** [comment]
This looks reasonable. There are two things to consider.

1) The code will still look at `/etc/pgbackrest.conf` if the config file does not exist in the specified location. Changing the code to ignore this file means also writing new test cases, which I'm not very excited about for a sandbox feature.
2) You have manually modified an auto-generated file so the changes actually need to be made in `build/lib/pgBackRestBuild/Config/BuildDefine.pm`. But it'd be easier for me to make that change since I know exactly how.

@mbanck Does that look reasonable to you, esp #1?

**Comment by mbanck** [comment]
I've tested the PR now and it works fine for me, thanks!

**Comment by dwsteele** [comment]
OK, I finally got to updating code generation so defaults can be based on C constants. That makes this commit a lot smaller.

Can you `git pull https://github.com/pgbackrest/pgbackrest.git autoconf-configdir` with the updates? Github won't let me push this directly because there are updates in master to our github workflows.

**Comment by mschout** [comment]
Thanks!  I'll take a look at this over the weekend.

**Comment by mschout** [comment]
Looking at this now....

**Comment by mschout** [comment]
I think this one is ready to merge. Let me know if it needs anything else.

**Comment by dwsteele** [comment]
Looks good, thank you!

**Pull request merged**
