### PR TITLE
Support --set in JSON output for info command.

### PR DESCRIPTION
**Pull request by pgstef**
Hi,

To get some behavior consistency between json and text output in the info command, I imagined we could simply keep the backup section smaller by filtering backupLabel earlier.

This allow to specify the `--set` option with the json output without duplicating too much code.

Covering tests seem to run fine:
```
2021-08-27 11:49:27.835 P00   INFO: P1-T1/1 - vm=u20, module=command, test=info (7.87s)
2021-08-27 11:49:29.446 P00   INFO: tested modules have full coverage
2021-08-27 11:49:29.446 P00   INFO: writing C coverage report
2021-08-27 11:49:29.578 P00   INFO: TESTS COMPLETED SUCCESSFULLY (13s)
```

The json output seems usable:
```json
"backup":[
         {
            "archive":{
               "start":"000000010000000000000002",
               "stop":"000000010000000000000002"
            },
            "backrest":{
               "format":5,
               "version":"2.35"
            },
            "checksum-page-error":null,
            "database":{
               "id":1,
               "repo-key":1
            },
            "database-ref":[
               {
                  "name":"postgres",
                  "oid":13319
               }
            ],
            "info":{
               "delta":24225802,
               "repository":{
                  "delta":3001728,
                  "size":3001728
               },
               "size":24225802
            },
            "label":"20210827-092715F",
            "link":null,
            "prior":null,
            "reference":null,
            "tablespace":null,
            "timestamp":{
               "start":1630049235,
               "stop":1630049238
            },
            "type":"full"
         }
      ],
```

Please, let me know what you think about this,
Kind Regards,
Stefan

### CODE REVIEW

**Comment by dwsteele** [comment]
This looks reasonable, but we definitely need tests that show error, db, and tablespace format in json. Should be easy enough to add these after the equivalent text tests, definitely 1550 and 1567, and maybe 1601, 1643, 1708 if they add value.

**Comment by pgstef** [comment]
> This looks reasonable, but we definitely need tests that show error, db, and tablespace format in json. Should be easy enough to add these after the equivalent text tests, definitely 1550 and 1567, and maybe 1601, 1643, 1708 if they add value.

Thanks for your reply and review :-)
Sorry it took me so long to add those tests (manually formatting the json output). I'm not sure if I made the formatting right though.

That adds 5 tests:
```
1 - multi-repo, backup not found
2 - backup set requested
3 - multi-repo, backup set requested, found on repo2, report stanza and db over all repos
4 - backup set requested, no links
5 - backup set requested, no db and no checksum error
```
4 and 5 are very similar than 2. I'm not really sure about the value but it's there, so not really harmful imho.

Hope this fits what you had in mind :-)

**Review by dwsteele — CHANGES_REQUESTED** [review]
This looks good, but I'm not satisfied with the name of the existing key used for reporting these errors. It was fine for the text output, but now that we have to commit to putting it in the JSON I would like revisit the name. See #1519 for details.

**Comment by pgstef** [comment]
> This looks good, but I'm not satisfied with the name of the existing key used for reporting these errors. It was fine for the text output, but now that we have to commit to putting it in the JSON I would like revisit the name. See #1519 for details.

I don't think it will change anything on the code here, only in the tests. I can probably merge the integration branch into mine once your PR is merged and adapt the tests ?

**Comment by dwsteele** [comment]
I think it is fine to merge the changes in here and update the tests, but I would like to look at getting #1508 done first.

**Comment by andr-sokolov** [comment]
@dwsteele , can I help you to get this PR merged faster?

**Comment by dwsteele** [comment]
@andr-sokolov We were hoping to get the error type into this format, but I don't think that's going to happen any time soon. Probably it would be best to look in the original file to get specific errors rather than trying to store everything in the manifest.

@pgstef Could you update this patch so we can see about getting it committed?

**Comment by andr-sokolov** [comment]
@dwsteele , @pgstef This is my version of the updated patch https://github.com/arenadata/pgbackrest/commit/dc10afaa73f72e42f4c409a7c7a82a9c35f86da1

**Comment by pgstef** [comment]
> @pgstef Could you update this patch so we can see about getting it committed?

Sure, I'll have a look at it asap

**Comment by andr-sokolov** [comment]
I am sorry. There is an error in my previous patch. This is the patch that has all the checks passed successfully  https://github.com/arenadata/pgbackrest/pull/14

**Comment by pgstef** [comment]
@dwsteele, given all the modifications we had since this PR, the merge was a bit messy and I preferred to start fresh.

This should be good to review now. I kept the same logic (filter backup labels in backupList, and have the 5 tests mentioned previously) :smile:

**Comment by pgstef** [comment]
(I think we'll have a conflict with 381fd0a about `backupLabelMatch` but I'll merge it here and update that part tomorrow morning ;-) )

**Comment by dwsteele** [comment]
Yeah, I suspected that might be an issue. The annotations commit is now in main so merge whenever you like.

**Comment by pgstef** [comment]
> Yeah, I suspected that might be an issue. The annotations commit is now in main so merge whenever you like.

Done, the fix was pretty small ;-)

**Review by dwsteele — APPROVED** [review]

**Pull request merged**
