### PR TITLE
Add timezone offset to info command date/time output.

### PR DESCRIPTION
**Pull request by dwsteele**
This makes it easier to use timestamps from the info command directly in PostgreSQL recovery settings, especially the --target option.

Unable to get the command/info test to run on FreeBSD because of how permissions are handled, but the behavior does appear to be correct. Added command/info test to MacOS.

### CODE REVIEW

**Comment by dwsteele** [comment]
@philrhurst I'm not able to add you as a reviewer but it would be a good idea for you to test and make sure this meets your expectations.

**Comment by philrhurst** [comment]
This looks good to me @dwsteele - I built the `dwsteele:dev-info-tz` branch on a Rocky 8 instance with Community PG 15.

Thank you for doing this! It is a huge quality-of-life improvement.

```
$ sudo -u postgres pgbackrest info
stanza: demo
    status: ok
    cipher: none

    db (current)
        wal archive min/max (15): 000000010000000000000001/000000010000000000000003

        full backup: 20230618-195024F
            timestamp start/stop: 2023-06-18 19:50:24+00 / 2023-06-18 19:50:29+00
            wal start/stop: 000000010000000000000003 / 000000010000000000000003
            database size: 22MB, database backup size: 22MB
            repo1: backup set size: 2.9MB, backup size: 2.9MB
```

**Review by pgstef — APPROVED** [review]
The code change and tests look good the me.
Having the timezone displayed seems indeed a good feature to have :+1:

**Comment by dwsteele** [comment]
Thank you @pgstef and @philrhurst!

**Pull request merged**
