### PR TITLE
Clarify that repo-s3-role is not an ARN.

### PR DESCRIPTION
**Pull request by Isaacwhyuenac**
Update the description on the use of S3 role. Make it more clear.

### CODE REVIEW

**Comment by dwsteele** [comment]
What do you think of the updated phrasing in 4e62386502ccd?

Also, how would you like your name to appear in the release notes?

**Review by dwsteele — APPROVED** [review]

**Comment by Isaacwhyuenac** [comment]
Yes I would love to. Thanks @dwsteele.

**Comment by dwsteele** [comment]
Haha, that was a question. Would you like to appear in the release notes as `Isaacwhyuenac` or something else?

**Comment by Isaacwhyuenac** [comment]
As `Isaac Yuen`. Thanks @dwsteele.

**Pull request merged**
