### PR TITLE
Remove sudo from src/Makefile.

### PR DESCRIPTION
**Pull request by disco-stu**
make should be called in the correct context not calling sudo itself.

### CODE REVIEW

**Comment by dwsteele** [comment]
Agreed.  I'll get this into 2.01.  You'll patch this for 2.00?

**Comment by disco-stu** [comment]
I think so. Otherwise I would need to add sudo to Build-Dependencies.

**Comment by dwsteele** [comment]
Yeah, i'd rather not do that.

**Comment by dwsteele** [comment]
Committed at 6ca6424fb1.

**Pull request closed without merging**
