### PR TITLE
Rename page checksum error to error list in info text output.

### PR DESCRIPTION
**Pull request by dwsteele**
"file error" makes it clear that other errors may be reported. If checksum-page is true in the manifest but no checksum-page-error list is provided then the error is in alignment, i.e. the file size is not a multiple of the page size, with allowances made for a valid-looking partial page at the end of the file.

### CODE REVIEW

**Review by pgstef — COMMENTED** [review]
`file-error` makes it clear that there's a problem indeed. But then, the question for the user is where to find the extra info.

Should we add more examples in the docs to help people investigate (they might not have the backup logs anymore) or could we change the display to reflect "invalid page checksum"/"page misalignment in file" like in the backup log ?

**Comment by dwsteele** [comment]
> could we change the display to reflect "invalid page checksum"/"page misalignment in file" like in the backup log ?

I don't think this would scale very well. I'm working on adding more errors -- in the end there could be 5-10. I think we would need some kind of `--detail` option since there could be 100+k errors per file.

I'm starting to remember why we didn't put this data into the JSON output. We just haven't finalized what we want to do here enough to commit to a format.

**Comment by pgstef** [comment]
> I don't think this would scale very well. I'm working on adding more errors -- in the end there could be 5-10. I think we would need some kind of `--detail` option since there could be 100+k errors per file.
> 
> I'm starting to remember why we didn't put this data into the JSON output. We just haven't finalized what we want to do here enough to commit to a format.

Given all the errors would be in the backup manifest (I guess), it would be nice to reflect those errors in the `--set` text output imho. Running info globally or with json format gives you the overview and then you could investigate with a more detailed view a specific backup set. 

That could be a feature/PR on its own, so this one looks fine to me ;-)

**Review by pgstef — APPROVED** [review]

**Comment by dwsteele** [comment]
I started looking at #1508 and realized it was already making some of the changes in this commit. I think it would be better to name this field `error-list` and the new field added by #1508 `error`. So we'll have a global error flag that is always present and a list that is present when `--set` is specified.

Make sense?

**Comment by pgstef** [comment]
> I started looking at #1508 and realized it was already making some of the changes in this commit. I think it would be better to name this field `error-list` and the new field added by #1508 `error`. So we'll have a global error flag that is always present and a list that is present when `--set` is specified.
> 
> Make sense?

Totally make sense. The global report is just a flag indicating "oops, something went wrong, please investigate". And then, we have the details when `--set` is specified. we might even limit some deeper prints for the text output, given we'd be supposed to investigate manually...

So +1 with the latest change :-)

**Pull request merged**
