### PR TITLE
Fix PostgreSQL query performance for large datasets.

### PR DESCRIPTION
**Pull request by npdgm**
The asynchronous logic used to implement the query timeout is misusing `PQisBusy()`, which causes the wait handler throttling the consumption of command results. It can introduce a huge delay on a backup job up to `db-timeout` because of the back-off sequence. `PQconsumeInput()` appears to be reading 16KB at a time.

Following the recommendation of libpq, the fix is to watch the client socket for data availability and keep consuming results and checking for command busyness.

### CODE REVIEW

**Comment by npdgm** [comment]
This is a proposed and tested fix for #2458

**Comment by dwsteele** [comment]
We have a function available to do socket polling so I used that instead. The trick now will be getting the tests working but that shouldn't take too long.

**Comment by npdgm** [comment]
> We have a function available to do socket polling so I used that instead. The trick now will be getting the tests working but that shouldn't take too long.

Neat! Thanks a lot for swift response.

**Comment by npdgm** [comment]
We deployed this PR and are running tests. My coworker will keep you updated.

**Review by pgguru — APPROVED** [review]
The basic approach seems sane to me; look forward to hearing back on the status from the field.

**Comment by dwsteele** [comment]
> look forward to hearing back on the status from the field.

See the linked issue (#2458). For their use case the patch is over a million times faster. Really just a comment on how inefficient the current code is.

**Pull request merged**
