### PR TITLE
Add AWS IMDSv2 support.

### PR DESCRIPTION
**Pull request by nunopi**
@dwsteele  as discussed here: https://github.com/pgbackrest/pgbackrest/issues/1685, I'm opening this PR so we can work on adding AWS IMDSv2 support to the S3 repository code. 

As far as I understood, in order to support IMDSv2 authentication it is necessary to change the way that pgbackrest gets credentials for an associated IAM role:
On IMDSv1 it is sufficient to send a GET request to /latest/meta-data/iam/security-credential
On IMDSv2 it is necessary to get a token first from the /latest/api/token endpoint via a PUT request and then add it to the headers in the GET request for the temp credentials to the /latest/meta-data/iam/security-credential endpoint.

See official documentation here: [AWS official documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html)

I've tested this in an EC2 environment that only allows IMDSv2 auth and was able to interact with the configured S3 bucket so in my limited testing this PR does work as intended.
There are a couple of warnings during the build:
```storage/s3/storage.c: In function ‘storageS3AuthAuto’:
storage/s3/storage.c:323:9: warning: passing argument 1 of ‘httpHeaderAdd’ discards ‘const’ qualifier from pointer target type [enabled by default]
         httpHeaderAdd(header, S3_HEADER_IMDSV2_TOKEN_STR, this->token);
         ^
In file included from ./common/io/http/request.h:16:0,
                 from ./storage/s3/storage.intern.h:12,
                 from ./storage/s3/read.h:7,
                 from storage/s3/storage.c:19:
./common/io/http/header.h:27:13: note: expected ‘struct HttpHeader *’ but argument is of type ‘const struct HttpHeader * const’
 HttpHeader *httpHeaderAdd(HttpHeader *this, const String *key, const String *value);
             ^
storage/s3/storage.c: At top level:
cc1: warning: unrecognized command line option "-Wno-implicit-fallthrough" [enabled by default]
```

Please note that I'm not a C developer and there's probably issues with this patch since I've simply copy pasted functions I found and modified them to retrieve the IMDSv2 token. Also this doesn't handle falling back to IMDSv1 as discussed in https://github.com/pgbackrest/pgbackrest/issues/1685

### CODE REVIEW

**Comment by nunopi** [comment]
@dwsteele I'd appreciate if you could set Nuno Pires as my name in the release notes. Thanks! :smiley:

**Comment by dwsteele** [comment]
OK, added renewal on expiration and unit tests. Please give it a try.

**Comment by nunopi** [comment]
thanks @dwsteele I can confirm it is working fine in my IMDSv2 environment

**Comment by dwsteele** [comment]
OK, this is (I think) a final version that makes the following improvements:

- Allow failback to IMDSv1 when a token cannot be fetched.
- Move constants to function.
- Don't store token. It will generally expire before the credentials so this complexity is wasted.
- Set TTL based on configured timeouts.

**Comment by dwsteele** [comment]
@nunopi Just to clarify, I think it would be best to test the updates from MAR-09 before we commit this.

**Comment by nunopi** [comment]
@dwsteele I will test your latest changes in the upcoming days and report back here.
Thanks again!

**Comment by nunopi** [comment]
hi @dwsteele I've tested the latest build today and it seems to work fine, thanks!

**Review by dwsteele — APPROVED** [review]

**Pull request merged**
