### PR TITLE
Report backup file validation errors in backup.info.

### PR DESCRIPTION
**Pull request by pgstef**
Hi,

This is a proposal to report the page checksum error flag from backup manifest to `backup.info`, and show an additional text message in the `info` command.

`infoBackupLoadCallback` is responsible to ensure the key is returned even if not existing previously.
`info` will then have a new key to report the boolean and the error list separately. The error list will only be returned when requesting info for a specific backup set.
Imho, the key name change won't have any impact given it's only shown in json output and until PR #1501, json output didn't support `--set`.

```bash
$ pgbackrest info
...
        full backup: 20210909-092339F
            timestamp start/stop: 2021-09-09 09:23:39 / 2021-09-09 09:23:45
            wal start/stop: 000000010000000000000019 / 000000010000000000000019
            database size: 180.3MB, database backup size: 180.3MB
            repo1: backup set size: 11.9MB, backup size: 11.9MB

        incr backup: 20210909-092339F_20210909-092539I
            timestamp start/stop: 2021-09-09 09:25:39 / 2021-09-09 09:25:41
            wal start/stop: 00000001000000000000001B / 00000001000000000000001B
            database size: 180.3MB, database backup size: 547.3KB
            repo1: backup set size: 11.9MB, backup size: 48.8KB
            backup reference list: 20210909-092339F
            page checksum error(s) detected

$ pgbackrest info --stanza=xxx --set=20210909-092339F_20210909-092539I
...
        incr backup: 20210909-092339F_20210909-092539I
            timestamp start/stop: 2021-09-09 09:25:39 / 2021-09-09 09:25:41
            wal start/stop: 00000001000000000000001B / 00000001000000000000001B
            database size: 180.3MB, database backup size: 547.3KB
            repo1: backup set size: 11.9MB, backup size: 48.8KB
            backup reference list: 20210909-092339F
            database list: postgres (13319), test-checksums (16406)
            page checksum error: base/16406/16407
```

Coverage test seems good too:
```
2021-09-09 08:47:23.203 P00   INFO: P1-T1/1 - vm=f33, module=info, test=info-backup (6.07s)
2021-09-09 08:47:24.558 P00   INFO: tested modules have full coverage
2021-09-09 08:47:24.559 P00   INFO: writing C coverage report
2021-09-09 08:47:24.684 P00   INFO: TESTS COMPLETED SUCCESSFULLY (11s)
...
2021-09-09 08:46:44.044 P00   INFO: P1-T1/1 - vm=f33, module=command, test=info (8.08s)
2021-09-09 08:46:45.127 P00   INFO: tested modules have full coverage
2021-09-09 08:46:45.127 P00   INFO: writing C coverage report
2021-09-09 08:46:45.257 P00   INFO: TESTS COMPLETED SUCCESSFULLY (14s)
```

Many thanks in advance for your review :-)

### CODE REVIEW

**Comment by pgstef** [comment]
Updated with the checksum-page-error key renaming.

**Review by dwsteele — APPROVED** [review]
Did some renaming and updated tests in 30d0d8d81c and bfb0627f5ea.

**Comment by pgstef** [comment]
> Did some renaming and updated tests in [30d0d8d](https://github.com/pgbackrest/pgbackrest/commit/30d0d8d81c8a1076e950e837d8174efb06194ce2) and [bfb0627](https://github.com/pgbackrest/pgbackrest/commit/bfb0627f5ea52d00afeb396e21d139e0b9e8ea7e).

That's awesome. The global error status becomes very interesting for monitoring purposes and if we want to add more error types, we would only have to flip that switch on in `infoBackup.c` I guess.

Thanks for your help on this, the changes look great to me ! :-)

**Comment by dwsteele** [comment]
Something has been bothering me about this commit -- older backups in `backup.info` get set with `backup-error:false` when `backup.info` is saved. Also, backups that do not have `backup-error` set in `backup.info` are reported by the info command as not having errors. If we want to use this flag for expire logic, it should be accurate.

In a148d1113c6f7, change backupError to a Variant so it can be true, false, or NULL. Add load/save and info logic to match.

**Comment by pgstef** [comment]
> change backupError to a Variant so it can be true, false, or NULL. Add load/save and info logic to match.

It totally make sense indeed

**Pull request merged**
