### PR TITLE
Summarize backup reference list for info command text output.

### PR DESCRIPTION
**Pull request by pgstef**
As written in [this](https://github.com/orgs/pgbackrest/projects/3?pane=issue&itemId=66663000) project card, the backup reference list might get very long, and it seems like a good idea to move it with `--set`.

As a compromise, now display a summary like:
```
        incr backup: 20240712-080157F_20240712-133649I
            timestamp start/stop: 2024-07-12 13:36:49+02 / 2024-07-12 13:36:51+02
            wal start/stop: 000000010000000000000009 / 000000010000000000000009
            database size: 22.2MB, database backup size: 410.7KB
            repo1: backup size: 44KB
            backup reference total: 1 full, 1 diff, 1 incr
```

### CODE REVIEW

**Review by dwsteele — CHANGES_REQUESTED** [review]
The code looks fine to me but documentation needs to be updated. `backup reference list` needs to be updated to `backup reference total` in the info command and `backup reference list` needs to be added to the `set` option.

**Comment by pgstef** [comment]
> `backup reference list` needs to be updated to `backup reference total` in the info command and `backup reference list` needs to be added to the `set` option.

Thanks for the review!
Doc update proposal in ee13755 :-)

**Review by dwsteele — APPROVED** [review]
Made a minor doc edit. Looks good to me now!

**Comment by pgstef** [comment]
> Made a minor doc edit. Looks good to me now!

Cool :-) Thanks for the review!

**Pull request merged**
