### PR TITLE
S3 SSE-C encryption support.

### PR DESCRIPTION
**Pull request by udf2457**
As per #2279, suggestion for SSE-C support.

Note on implementation detail:

I left it as an excercise for the user to provide the base64-encoded 128-bit MD5 digest of the encryption key. Because otherwise it would mean doing `md5(base64decode(userProvidedKey))`,  which would all get very messy, especially as you don't have existing base64 decoding in place.

Also from an integrity checking perspective, enforcing it on the user to provide both parameters means we are providing for end-to-end integrity (i.e. the user is the source of truth of the integrity check, not a `pgbackrest` function).

### CODE REVIEW

**Comment by dwsteele** [comment]
> Also from an integrity checking perspective, enforcing it on the user to provide both parameters means we are providing for end-to-end integrity

AWS' boto does not require this and nor should we. The purpose of the field according the the docs is to ensure transmission integrity not to make the user's life hard. All the necessary function are present in pgBackRest so generating the field automatically is no problem.

> suggestion for SSE-C support.

The goal here was to get a mockup that had actually been compiled and tested. However, I have provided an implementation based on the documentation with zero real-world testing. Please compile and run through at least all the steps in the quickstart using the new feature (https://pgbackrest.org/user-guide.html#quickstart) at a minimum.

**Comment by udf2457** [comment]
Apologies for the delay on this @dwsteele, have been busy at $work, but am hoping to test it over the next couple of days. 

Test and compile off main branch, right ?

**Comment by dwsteele** [comment]
> Test and compile off main branch, right ?

Yes, main branch in the https://github.com/udf2457/pgbackrest repo.

**Comment by udf2457** [comment]
Apologies, I don't know my way around `meson`.

I cloned my repo but `meson` is refusing to have to do anything with it:

`build/pgbackrest/doc/src/meson.build:5:4: ERROR: Problem encountered: meson is currently not supported for release builds
`

**Comment by dwsteele** [comment]
This branch has not been updated in a while so it predates us enabling meson. I've updated the branch and it should work with meson now.

Alternately you could use the autoconf/make build, which is deprecated but still works: https://pgbackrest.org/user-guide-rhel.html#build

**Comment by udf2457** [comment]
@dwsteele 

Tested using quickstart with the following config:

```
[demo]
pg1-path=/var/lib/postgresql/16/main

[global]
repo1-retention-full=2
repo1-type=s3
repo1-s3-endpoint=<REMOVED FOR SECURITY>
repo1-s3-bucket=<REMOVED FOR SECURITY>
repo1-s3-key=<REMOVED FOR SECURITY>
repo1-s3-key-secret=<REMOVED FOR SECURITY>-ixYnisz4e4Vy57sVZP4
repo1-s3-region=ch-gva-2
repo1-s3-sse-customer-key=<REMOVED FOR SECURITY>
```

It was tested against [Exoscale SOS](https://community.exoscale.com/documentation/storage/encryption/)

**Comment by udf2457** [comment]
As an aside @dwsteele , you need to do whatever you need to do to ensure gets replaced with `<redacted>` for `repo1-s3-sse-customer-key`, like you already do for `s3-key-secret` etc.

**Comment by dwsteele** [comment]
> you need to do whatever you need to do to ensure the SSE key gets replaced with <redacted>

Ah yes, good point. Done in 74562d5a.

> but your docs don't mention the requirement for head-*

These are not required on standard S3. My guess is HEAD is implied by GET, which makes a lot of sense since HEAD is just GET without the content.

**Review by dwsteele — APPROVED** [review]
OK, this looks good to me now, and works fine on regular S3.

**Comment by dwsteele** [comment]
@udf2457 How would you like your name to appear in the release notes?

**Comment by udf2457** [comment]
@dwsteele Tim Jones

Thanks again for your help making this happen !

**Comment by dwsteele** [comment]
> Thanks again for your help making this happen !

You are welcome!

**Pull request merged**
