### PR TITLE
Makefile misc

### PR DESCRIPTION
**Pull request by fluca1978**
A few minor changes to the makefile with the hope of making it a little more usable.

### CODE REVIEW

**Comment by dwsteele** [comment]
The clean and uninstall targets are easy enough.  

Not sure about DESTDIR, though.  I know that making the change you or @hunleyd (#662) have suggested will break the Debian package build.  But, looking at the package source, it seems like we just need to update:

https://salsa.debian.org/postgresql/pgbackrest/blob/master/debian/rules#L37

@disco-stu Does that look right to you?

**Comment by dwsteele** [comment]
Committed clean and uninstall targets at 3d7edc4c.

**Comment by disco-stu** [comment]
The purposed patch looks good. I'll update the Debian package accordingly.

**Comment by dwsteele** [comment]
@disco-stu I'll need to write a patch anyway or the integration tests won't pass (since they build packages).  I'll provide that for the release (coming soon), though I doubt you'll need it.

**Comment by dwsteele** [comment]
The DESTDIR part of this was commited at 786e77a based on Doug's patch in #662.

**Pull request closed without merging**
