### PR TITLE
Add archive-mode-check option.

### PR DESCRIPTION
**Pull request by pgstef**
As discussed in #1286.

Test system is currently failing on my laptop:
```
2021-02-02 11:12:20.722 P00   INFO: P1-T1/1 - vm=u18, module=command, test=check (8.4s)
2021-02-02 11:12:22.185 P00  ERROR: [125]: c module command/check/common is not fully covered (34/36 branches)
2021-02-02 11:12:22.185 P00   INFO: writing C coverage report
2021-02-02 11:12:22.591 P00  ERROR: [125]: function not found at line 000000082
function not found at line 000000082
 at pgbackrest/test/lib/pgBackRestTest/Common/CoverageTest.pm line 399.
	pgBackRestTest::Common::CoverageTest::coverageGenerateFunction(HASH(0x562155e65640), 000000082) called at pgbackrest/test/lib/pgBackRestTest/Common/CoverageTest.pm line 491
	pgBackRestTest::Common::CoverageTest::coverageGenerate(pgBackRestTest::Common::Storage=HASH(0x5621559e1cf8), "/home/vagrant/test/repo", "/home/vagrant/pgbackrest/test/result/coverage/raw", "/home/vagrant/pgbackrest/test/result/coverage/coverage.html") called at pgbackrest/test/lib/pgBackRestTest/Common/CoverageTest.pm line 355
	pgBackRestTest::Common::CoverageTest::coverageValidateAndGenerate(ARRAY(0x562155e35580), pgBackRestTest::Common::Storage=HASH(0x5621559e1cf8), 1, 0, "/home/vagrant/test", "/home/vagrant/test/temp", "/home/vagrant/pgbackrest/test/result", "/home/vagrant/pgbackrest/doc/xml/auto") called at pgbackrest/test/test.pl line 1130
	eval {...} called at pgbackrest/test/test.pl line 1197
```

I'll try to figure that out and add the tests for this feature.

Edit: Thanks to the github actions, I was able to run the tests on my laptop too using the `f32` vm. I hope the added tests are enough.

### CODE REVIEW

**Review by dwsteele — APPROVED** [review]
A few adjustments:
1) Make archive-mode-check depend on archive-check like archive-copy does.
2) Add caution to the option.
3) New tests should get a TEST_TITLE(). This module is old enough that it doesn't have any.
4) Minor typos and formatting.

**Comment by dwsteele** [comment]
> I was able to run the tests on my laptop too using the f32 vm

Sometime last year the u18 vm stopped working reliably with coverage. Not sure if it's a problem with our code or something that got broken on u18. Newer gcc seems fine (f32, u20) so I haven't bothered to go back and figure it out.

**Comment by dwsteele** [comment]
@mbanck please have a look and make sure this does what you are expecting.

**Comment by mbanck** [comment]
> @mbanck please have a look and make sure this does what you are expecting.

I tested it and it seems to work fine, thanks!

**Comment by cmwshang** [comment]
Since the new option is dependent on CFGOPT_ARCHIVE_CHECK, would it not be prudent to have an integration or other test for determining how this will affect the backup command?

**Comment by dwsteele** [comment]
I think it's OK since backup does not use CFGOPT_ARCHIVE_MODE_CHECK directly. it just uses checkDbConfig() which is covered in the `command/check` module.

**Pull request merged**
